---
- name: Add authorized key
  hosts: all
  remote_user: root
  vars_prompt:
    - name: file
      prompt: "Public key file"
      private: false
      default: "~/.ssh/id_ed25519.pub"
  tasks:
    - name: Add user authorized key
      ansible.posix.authorized_key:
        user: root
        key: "{{ lookup('file', file) }}"
