---
- name: Add authorized key
  hosts: manager
  remote_user: root
  vars_prompt:
    - name: file
      prompt: "Public key file"
      private: false
      default: "~/.ssh/id_ed25519.pub"
  tasks:
    - name: Add user authorized key
      authorized_key:
        user: deploy
        key: "{{ lookup('file', file) }}"
