---
- name: Upgrade
  hosts: all
  remote_user: root
  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade APT to the latest packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Remove useless packages
      ansible.builtin.apt:
        autoclean: true

    - name: Remove useless dependencies
      ansible.builtin.apt:
        autoremove: true
