---
- name: Install htop
  ansible.builtin.apt:
    name:
      - htop
    state: present
    update_cache: true

- name: Install cockpit
  ansible.builtin.apt:
    name:
      - cockpit
    state: present
    update_cache: true
  notify: Start cockpit on boot
