---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg
    state: present
    update_cache: true

- name: Add GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Verify fingerprint
  ansible.builtin.apt_key:
    id: 0EBFCD88
    state: present

- name: Set up the repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable
    state: present
    filename: docker
    update_cache: true

- name: Install Docker
  ansible.builtin.apt:
    name: docker-ce
    state: present
    update_cache: true
  notify: Start docker on boot

- name: Install Docker Compose
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/v2.14.2/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
    dest: /usr/local/bin/docker-compose
    force: true
    group: docker
    mode: 'u+x,g+x'

- name: Set periodic Docker prune
  ansible.builtin.cron:
    name: docker-prune
    job: 'docker system prune -af --filter until=720h'
    minute: '0'
    hour: '1'

- name: Remove useless packages
  ansible.builtin.apt:
    autoclean: true

- name: Remove useless dependencies
  ansible.builtin.apt:
    autoremove: true
