---
- name: Install Docker SDK dependencies
  ansible.builtin.apt:
    name:
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: present
    update_cache: true

- name: Install Docker SDK for Python
  ansible.builtin.pip:
    name: docker
