version: '3.9'
services:
  cluster-redis:
    image: ${REGISTRY}/cluster-redis:${IMAGE_TAG}
    volumes:
      - cluster-redis:/data
    environment:
      - REDIS_PASSWORD
    command:
      - 'redis-server'
      - '--maxmemory 32mb'
      - '--maxmemory-policy allkeys-lru'
    ports:
      - '6379:6379'
    deploy:
      placement:
        constraints: [node.labels.db == db]

volumes:
  cluster-redis:
