name: Build and Push docker images

on:
  push:

env:
  REGISTRY: ghcr.io/${{ github.repository }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Inject branch slug
        uses: rlespinasse/github-slug-action@v2.x

      - name: Set image tag
        run: echo "IMAGE_TAG=${{ env.GITHUB_REF_SLUG }}" >> $GITHUB_ENV

      - name: Build images
        run: make build

      - name: Push images
        run: make push
        if: ${{ github.ref == 'refs/heads/main' }}
