name: Lint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@main
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_data: "{extends: relaxed, rules: {line-length: disable}}"
          strict: true
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
